@startuml
class book {
{field} id: integer
{field} isbn: text
{field} name: text
{field} author: text
}
class annotation {
{field} id: integer
{field} book_id: integer
{field} text: text
{field} location: text
{field} ts: timestamp
{field} origin: text
{field} type: text
}
book "1" -- "0..*" annotation
@enduml
